# Generated by Django 5.0.6 on 2024-06-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_student_img_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='student_img',
            new_name='gallery_img',
        ),
    ]
