# Generated by Django 5.0.6 on 2024-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_datapoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='label',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='value',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='labels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='values',
            field=models.JSONField(default=list),
        ),
    ]
