# Generated by Django 5.0.6 on 2024-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, null=True, upload_to='student/'),
        ),
    ]
