# Generated by Django 5.0.6 on 2024-06-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_numberarray'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
